<Project>
  <ItemGroup>
    <PackageVersion Include="Humanizer.Core" Version="2.14.1" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
  </ItemGroup>
</Project>
